#!/bin/bash

#
# Logs the container shutdown
# ===========================
#

set -e

. /usr/local/lib/utils.inc
. /usr/local/lib/env.inc

# Load the runtime environment
load_env

log_info 'Stopping the container'
