#!/usr/bin/with-contenv /bin/bash

#
# Sets up the runtime environment 
# ===============================
#

set -e

# Use the build environment values as defaults for the container environment
. /etc/environment
. /usr/local/lib/env.inc

# Copy the container environment to the runtime environment,
# removing the leading 'T3_' from variable names
set_env $(env)
