#!/usr/bin/with-contenv /bin/bash

#
# Configures the platform and starts logging
# ==========================================
#

set -e

# Use the build environment values as defaults for the container environment
. /etc/environment
. /usr/local/lib/env.inc
. /usr/local/lib/utils.inc

# Copy the container environment to the runtime environment,
# removing the leading 'T3_' from variable names
save_env

# Load the runtime environment
load_env


# Try to determine the local timezone if none was specified
if [ -z "$T3_TIMEZONE" ]; then
    T3_TIMEZONE="$(curl -s https://ipapi.co/timezone)"
fi

# Use timezone if specified and supported
if [ -n "$T3_TIMEZONE" ]; then
    if [ -f "/usr/share/zoneinfo/${T3_TIMEZONE}" ]; then
        ln -sf /usr/share/zoneinfo/${T3_TIMEZONE} /etc/localtime
        set_var TIMEZONE $T3_TIMEZONE
    else
        err_exit "Unsupported timezone: $T3_TIMEZONE"
    fi
fi


# Remove empty log files installed by syslog-ng
rm -f /var/log/*.log

# Optional destination for BSD syslog host
if [ -n "$LOG_HOST_IP" ]; then
    test -n "$LOG_HOST_PORT" || LOG_HOST_PORT=514
    LOG_HOST_DEST="destination { network(\"$LOG_HOST_IP\" port($LOG_HOST_PORT) transport(\"udp\")); };"
else
    LOG_HOST_DEST=
fi

# Build the configuration file (escaping '$' needs an ugly hack)
mkdir -p /etc/syslog-ng
D='$' envsubst >/etc/syslog-ng/typo3.conf <<EOT
@version:3.22

options {
    # Create destination directories if missing
    create_dirs(no);
    dir_perm(0755);

    # Default owner, group, and permissions for log files
    owner(root);
    group(wheel);
    perm(0640);

    # Log a STATS line every 12 hours
    stats_freq(43200);

    # Wait 5s before re-establishing a died connection
    time_reopen(5);

    # Avoid DNS lookups
    use_dns(no);
    dns_cache(no);
};

source s_local { internal(); system(); };

source s_apache_access { pipe("$APACHE_LOGS/access"); };

source s_apache_error { pipe("$APACHE_LOGS/error"); };

source s_mysql_error { pipe("$MYSQL_LOGS/error"); };

template t_container {
    template("[\${D}{R_YEAR}-\${D}{R_MONTH}-\${D}{R_DAY} \${D}{R_HOUR}:\${D}{R_MIN}:\${D}{R_SEC}.\${D}{R_MSEC} \${D}{R_TZOFFSET}] \${D}{LEVEL} \${D}{MSGHDR}\${D}{MSG}\\n");
};

log { 
    source(s_local);
    source(s_apache_access);
    source(s_apache_error);
    source(s_mysql_error);
    destination { file("$STDOUT" template(t_container) frac_digits(3)); };
    $LOG_HOST_DEST
};
EOT

syslog-ng -f /etc/syslog-ng/typo3.conf


# Show OS version
log_info "Alpine Linux $(cat /etc/alpine-release)"

# Show locale
log_info "Locale: $LANG"

# Show timezone
test -n "$T3_TIMEZONE" && log_info "Timezone: $T3_TIMEZONE ($(date +%Z))" || log_info "No timezone set ($(date +%Z))"
