#!/bin/bash

#
# Sets up the selected database service
# =====================================
#

set -e

. /usr/local/lib/utils.inc
. /usr/local/lib/env.inc

# Load the runtime environment
load_env

# Accept abbreviated database types, ignore case
T3_DB_TYPE=${T3_DB_TYPE:-sqlite}
declare -A DB_TYPES
DB_TYPES=([mariadb]= [postgresql]= [sqlite]=)

for T in ${!DB_TYPES[@]}; do
    if [[ ${T} == ${T3_DB_TYPE,,}* ]]; then
        # Set up the selected database
        . /usr/local/lib/${T}.inc

        # Deactivate logging services for unselected databases
        unset DB_TYPES[$T]
        for U in ${!DB_TYPES[@]}; do
            rm -rf /etc/services.d/${U}/
        done

        exit
    fi
done

err_exit "Unknown database type: '$T3_DB_TYPE'"
